/*
 * Copyright (c) 2026 Samantha Ireland
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package ca.samanthaireland.stormstack.thunder.controlplane.node.model;

import java.time.Instant;
import java.util.Objects;

/**
 * Represents a Lightning Engine node in the cluster.
 *
 * @param nodeId          unique identifier for this node (generated by node)
 * @param advertiseAddress URL where this node can be reached (e.g., http://node1:8080)
 * @param status          current status (HEALTHY or DRAINING)
 * @param capacity        capacity limits for this node
 * @param metrics         current metrics from the node
 * @param registeredAt    when the node first registered
 * @param lastHeartbeat   when the node last sent a heartbeat
 */
public record Node(
        NodeId nodeId,
        String advertiseAddress,
        NodeStatus status,
        NodeCapacity capacity,
        NodeMetrics metrics,
        Instant registeredAt,
        Instant lastHeartbeat
) {

    public Node {
        Objects.requireNonNull(nodeId, "nodeId cannot be null");
        Objects.requireNonNull(advertiseAddress, "advertiseAddress cannot be null");
        Objects.requireNonNull(status, "status cannot be null");
        Objects.requireNonNull(capacity, "capacity cannot be null");
        Objects.requireNonNull(metrics, "metrics cannot be null");
        Objects.requireNonNull(registeredAt, "registeredAt cannot be null");
        Objects.requireNonNull(lastHeartbeat, "lastHeartbeat cannot be null");

        if (advertiseAddress.isBlank()) {
            throw new IllegalArgumentException("advertiseAddress cannot be blank");
        }
    }

    /**
     * Creates a new node upon registration.
     *
     * @param nodeId          the node's unique identifier
     * @param advertiseAddress the URL where the node can be reached
     * @param capacity        the node's capacity limits
     * @return a new Node in HEALTHY status with empty metrics
     */
    public static Node register(NodeId nodeId, String advertiseAddress, NodeCapacity capacity) {
        Instant now = Instant.now();
        return new Node(
                nodeId,
                advertiseAddress,
                NodeStatus.HEALTHY,
                capacity,
                NodeMetrics.empty(),
                now,
                now
        );
    }

    /**
     * Creates a new node upon registration using a string node ID.
     *
     * @param nodeId          the node's unique identifier as string
     * @param advertiseAddress the URL where the node can be reached
     * @param capacity        the node's capacity limits
     * @return a new Node in HEALTHY status with empty metrics
     */
    public static Node register(String nodeId, String advertiseAddress, NodeCapacity capacity) {
        return register(NodeId.of(nodeId), advertiseAddress, capacity);
    }

    /**
     * Creates a new node with updated metrics and heartbeat time.
     *
     * @param metrics the new metrics
     * @return a new Node with updated metrics and lastHeartbeat
     */
    public Node withHeartbeat(NodeMetrics metrics) {
        return new Node(
                nodeId,
                advertiseAddress,
                status,
                capacity,
                metrics,
                registeredAt,
                Instant.now()
        );
    }

    /**
     * Creates a new node with DRAINING status.
     *
     * @return a new Node with DRAINING status
     */
    public Node drain() {
        return new Node(
                nodeId,
                advertiseAddress,
                NodeStatus.DRAINING,
                capacity,
                metrics,
                registeredAt,
                lastHeartbeat
        );
    }

    /**
     * Checks if the node can accept new containers.
     *
     * @return true if the node is healthy and has capacity
     */
    public boolean canAcceptContainers() {
        return status == NodeStatus.HEALTHY
                && metrics.containerCount() < capacity.maxContainers();
    }

    /**
     * Returns the number of available container slots.
     *
     * @return available slots, or 0 if draining
     */
    public int availableCapacity() {
        if (status == NodeStatus.DRAINING) {
            return 0;
        }
        return Math.max(0, capacity.maxContainers() - metrics.containerCount());
    }
}
